main: de.timesnake.game.survivalgames.main.GameSurvivalGames
version: 1.3.0
name: game-hungergames
author: timesnake
api-version: 1.13
depend: [ basic-lounge-bridge ]

commands:
  hg:
    aliases:
      - hungergames

