main: de.timesnake.game.survivalgames.main.GameSurvivalGames
version: ${version}
name: game-hungergames
author: timesnake
api-version: 1.21
depend: [ basic-lounge-bridge ]

commands:
  hg:
    aliases:
      - hungergames

